spring:
  datasource:
    url: jdbc:h2:file:./data/autocheck-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Opcjonalnie włącz konsolę H2
server:
  port: 8080

spring.h2.console:
  enabled: true
  path: /h2-console
